# Generated by Django 3.1.2 on 2020-10-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0, max_length=10)),
                ('availability', models.BooleanField()),
                ('description', models.CharField(default='Please buy this. The seller is broke and needs the money', max_length=250)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
