# Generated by Django 3.1.2 on 2020-10-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(default='SELECT CATEGORY', on_delete=django.db.models.deletion.CASCADE, to='Store.category'),
        ),
    ]
