# Generated by Django 3.1.2 on 2020-10-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
