# Generated by Django 3.1.2 on 2020-10-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_auto_20201011_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
